### ISSUE TITLE
Check several packages in parallel

### ISSUE THREAD

**Issue by Mic92** [makefu/hydra-check#2]
It would be great if the channel argument would become a parameter and
one could pass multiple packages.
i.e nix-review outputs a list of failed packages: https://github.com/NixOS/nixpkgs/pull/82866#issuecomment-600868331

usage: hydra-check [--channel=version] PACKAGE [PACKAGES...]

**Comment by makefu** [comment]
how should the json output look like? something like this maybe:
```
{
  "package1" : [],   // list of successful and failed builds for package1
  "package2" : [],   // list of successful and failed builds for package2
}
```

**Comment by Mic92** [comment]
Looks good.

**Comment by billoreraja4-blip** [comment]
Instagram password cerak
