### ISSUE TITLE
Very slow installation

### ISSUE THREAD

**Issue by dvzubarev** [makefu/hydra-check#33]
Steps to reproduce:
1. clone repository
2. `time nix-shell --run "hydra-check  python310Packages.faiss"`
```
...
these 183 paths will be fetched (418.20 MiB download, 2159.73 MiB unpacked)
...
these 77 derivations will be built:
...
real    3m38,434s
```
3. Compare it with the installation time of the previous version
4. nix-collect-garbage
5. `git checkout 8bd45f8cef8b9ac27c99513ec260e92705db681f`
6. `time nix-shell --run "hydra-check  python310Packages.faiss"`
```
real    0m2,014s
```

I do `nix-collect-garbage` pretty regularly so its painfully slow to use this tool every time I need it. 
Its good that I remembered that it was fast when I used it first time .
So any other poor soul, who just wants to quickly run 200-line python script, use the previous version: 8bd45f8cef8b9ac27c99513ec260e92705db681f.

**Comment by makefu** [comment]
Hi, i am unsure how using an older version changes your download time, maybe your nixpkgs channel does not fit your system channel? Another possibility could be that accidentally the dependencies of the old version of hydra-check are cached by one of your other active derivations. Check out https://nixos.wiki/wiki/Storage_optimization#Look_for_result_symlinks

I checked the diff between 1.3.4 and 1.3.0 but actually 1.3.4 contains fewer dependencies: `docopt` and `types-docopt`were removed.
Apart from that, hydra-check has `requests`,`colorama` and `beautifulsoup` as dependencies, which is really not that much.
I am closing this issue for now, not sure how else i could help here.

**Comment by dvzubarev** [comment]
> I am closing this issue for now, not sure how else i could help here.

I am fine with it. I created this issue for discoverability.

> he old version of hydra-check are cached by one of your other active derivations

I tried in clean environment:

1. `docker run -ti nixos/nix`
2. `nix-channel --update`
3.  clone *latest* version `git clone https://github.com/nix-community/hydra-check.git`
4. `time nix-shell --run "hydra-check  python310Packages.faiss"`
```
...
these 37 derivations will be built:
...
these 218 paths will be fetched (197.79 MiB download, 916.08 MiB unpacked):
...
real    1m45.961s
```
5. nix-collect-garbage
6. `git checkout 8bd45f8cef8b9ac27c99513ec260e92705db681f`
7. `time nix-shell --run "hydra-check  python310Packages.faiss"`
```
these 105 paths will be fetched (117.38 MiB download, 499.12 MiB unpacked):
...
real    0m12.477s
```
I need to say that your recent changes helped a lot.

Checkout revision that was latest when I opened this issue.
8. nix-collect-garbage
9. `git checkout 876324f114983429a6aaae4af7fd87e2eabf5eee`
10.  `time nix-shell --run "hydra-check  python310Packages.faiss"`
```
...
these 77 derivations will be built:
...
these 226 paths will be fetched (480.58 MiB download, 2349.08 MiB unpacked):
...
real    4m58.780s
```
  
My personal takeaway from this, is not to use poetry2nix in my personal projects.
