### ISSUE TITLE
Add to Nixpkgs?

### ISSUE THREAD

**Issue by doronbehar** [makefu/hydra-check#6]
Hey, `hydra-check` is very useful. It'd be nice to have it in Nixpkgs.

**Comment by makefu** [comment]
Now that the tool is stable and feature-complete™ i will prepare a PR :)

**Comment by bhipple** [comment]
This issue can be closed now!

**Comment by doronbehar** [comment]
Is anyone working on the update to 2.0.0 in Nixpkgs ? If not I can help :).

**Comment by doronbehar** [comment]
Nixpkgs Update at:

- https://github.com/NixOS/nixpkgs/pull/359514

An issue that was observed right after the update, which might be better to fix before updating the package, is:

- https://github.com/nix-community/hydra-check/issues/54
