### ISSUE TITLE
check a specific jobset ?

### ISSUE THREAD

**Issue by teto** [makefu/hydra-check#7]
hi,

is there a way to check a specific jobset that is not a channel ? I wouldl ike to check https://hydra.nixos.org/jobset/nixpkgs/structured-attrs for instance.

Also I have trouble remembering the different platform so it would be nice if the help would list them.
Thanks for the cool tool.

**Comment by makefu** [comment]
This is actually already supported:
```
hydra-check hello --channel nixpkgs/structured-attrs
```
Jobset is probably a better name than `--channel`, however i added a bit of guessing logic to find out what the user is probably looking for
